export const data=[
    {
        id: Math.floor(Math.random() * 100),
        img: undefined,
        name: 'Rudgram',
        surname: 'Community',
        message: 'Rudgram Web updated to 15.0.2 version',
        messageNum: '1',
    },
    {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1629467057571-42d22d8f0cbd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=398&q=80',
        name: 'Ronald',
        surname: 'Will',
        message: 'Where r u?',
        messageNum: '5',
    },
    {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
        name: 'Suzan',
        surname: 'Nilu',
        message: 'Do your homework?',
        messageNum: '250',
    },
    {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80',
        name: 'Maria',
        surname: "Belov",
        message:  "Lewis: All done mate 😆  ",
        messageNum: '',
    }, {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1542329769-aabef9e9b3c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
        name: 'Nikita',
        surname: 'Belov',
        message: 'Im going to university, will you come today?',
        messageNum: '1',
    }, {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80',
        name: 'Nyan',
        surname: 'Cyuzu',
        message: 'Ok, see you later',
        messageNum: '2',
    }, {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1553521041-d168abd31de3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80',
        name: 'Eugene',
        surname: 'Smith',
        message: "Sorry dude, i'm busy on this weekends...",
        messageNum: '1',
    }, {
        id: Math.floor(Math.random() * 100),
        img: 'https://images.unsplash.com/photo-1623479322729-28b25c16b011?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
        name: 'Developers',
        surname: 'Team',
        message: 'You: i don\'t remember anything 😄 ',
        messageNum: '',
    }, {
        id: Math.floor(Math.random() * 100),
        img: 'https://yt3.ggpht.com/MRywaef1JLriHf-MUivy7-WAoVAL4sB7VHZXgmprXtmpOlN73I4wBhjjWdkZNFyJNiUP6MHm1w=s900-c-k-c0x00ffffff-no-rj',
        name: 'BBC',
        surname: 'News',
        message: 'Japan\'s police to take measures after wild monkey rampages',
        messageNum: '7',
    }
]
